version: "3.9"

services:

  server:
    build: ./server
    container_name: medical-server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  client:
    build: ./client
    container_name: medical-client
    ports:
      - "8501:8501"
    depends_on:
      - server
    environment:
      - API_URL=http://server:8000